// Compiles global.scss and every *.module.scss under app/ with Sass, then runs the
// result through lightningcss for CSS Modules (scoped class and keyframe names).
// Output: public/css/main.css plus a typed `<name>.module.scss.ts` beside each module,
// exporting the local-name -> scoped-name map that components import.
import { mkdirSync, readdirSync, statSync, watch, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { transform } from 'lightningcss'
import * as sass from 'sass'

const root = process.cwd()
const appDir = join(root, 'app')
const outFile = join(root, 'public/css/main.css')
const globalEntry = join(appDir, 'styles/global.scss')

function findModules(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    let path = join(dir, name)
    if (statSync(path).isDirectory()) return findModules(path)
    return name.endsWith('.module.scss') ? [path] : []
  })
}

function compile(file: string) {
  return sass.compile(file, { loadPaths: [join(appDir, 'styles')], style: 'expanded' }).css
}

function build() {
  let css = [compile(globalEntry)]

  for (let file of findModules(appDir).sort()) {
    let result = transform({
      filename: file,
      code: Buffer.from(compile(file)),
      cssModules: true,
    })
    css.push(result.code.toString())

    let exports = Object.fromEntries(
      Object.entries(result.exports ?? {}).map(([local, { name }]) => [local, name]),
    )
    writeFileSync(
      file + '.ts',
      `// Generated by scripts/build-css.ts. Do not edit.\nexport default ${JSON.stringify(exports, null, 2)} as const\n`,
    )
  }

  mkdirSync(join(root, 'public/css'), { recursive: true })
  writeFileSync(outFile, css.join('\n'))
  console.log(`css: built ${relative(root, outFile)}`)
}

build()

if (process.argv.includes('--watch')) {
  let timer: ReturnType<typeof setTimeout> | undefined
  watch(appDir, { recursive: true }, (_event, name) => {
    if (!name?.endsWith('.scss')) return
    clearTimeout(timer)
    timer = setTimeout(() => {
      try {
        build()
      } catch (error) {
        console.error(error)
      }
    }, 50)
  })
}
